package updated.mysterium.vpn.exceptions

class ConnectAlreadyExistsException(message: String) : Exception(message)
